/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Oscar Marcía - Programmer Analyst
 */
public class menu_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form menu_usuarios
     */
    public menu_usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layout_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo_label = new javax.swing.JLabel();
        nav_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nav_header = new javax.swing.JPanel();
        logo_label1 = new javax.swing.JLabel();
        sidebar1 = new javax.swing.JPanel();
        sidebar2 = new javax.swing.JPanel();
        sidebar3 = new javax.swing.JPanel();
        sidebar4 = new javax.swing.JPanel();
        lowerbar1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        layout_panel.setBackground(new java.awt.Color(153, 204, 255));
        layout_panel.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(null);

        logo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/icons/logo-black-130.png"))); // NOI18N
        logo_label.setText("<html></html>");
        logo_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(logo_label);
        logo_label.setBounds(120, 30, 70, 80);

        layout_panel.add(jPanel2);
        jPanel2.setBounds(-10, -10, 360, 140);

        nav_panel.setBackground(new java.awt.Color(153, 204, 255));
        nav_panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nav_panel.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Navegación");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_panel.add(jLabel2);
        jLabel2.setBounds(30, 10, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Usuarios");
        nav_panel.add(jLabel3);
        jLabel3.setBounds(30, 110, 100, 15);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Inicio");
        nav_panel.add(jLabel4);
        jLabel4.setBounds(30, 70, 100, 15);

        layout_panel.add(nav_panel);
        nav_panel.setBounds(0, 130, 350, 680);

        nav_header.setBackground(new java.awt.Color(102, 204, 255));
        nav_header.setLayout(null);

        logo_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/icons/logo-black-250.png"))); // NOI18N
        logo_label1.setText("<html></html>");
        logo_label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_header.add(logo_label1);
        logo_label1.setBounds(660, 0, 170, 120);

        layout_panel.add(nav_header);
        nav_header.setBounds(350, 0, 860, 130);

        sidebar1.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout sidebar1Layout = new javax.swing.GroupLayout(sidebar1);
        sidebar1.setLayout(sidebar1Layout);
        sidebar1Layout.setHorizontalGroup(
            sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        sidebar1Layout.setVerticalGroup(
            sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        layout_panel.add(sidebar1);
        sidebar1.setBounds(350, 130, 30, 220);

        sidebar2.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout sidebar2Layout = new javax.swing.GroupLayout(sidebar2);
        sidebar2.setLayout(sidebar2Layout);
        sidebar2Layout.setHorizontalGroup(
            sidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        sidebar2Layout.setVerticalGroup(
            sidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        layout_panel.add(sidebar2);
        sidebar2.setBounds(1180, 130, 30, 220);

        sidebar3.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout sidebar3Layout = new javax.swing.GroupLayout(sidebar3);
        sidebar3.setLayout(sidebar3Layout);
        sidebar3Layout.setHorizontalGroup(
            sidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        sidebar3Layout.setVerticalGroup(
            sidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        layout_panel.add(sidebar3);
        sidebar3.setBounds(350, 350, 30, 460);

        sidebar4.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout sidebar4Layout = new javax.swing.GroupLayout(sidebar4);
        sidebar4.setLayout(sidebar4Layout);
        sidebar4Layout.setHorizontalGroup(
            sidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        sidebar4Layout.setVerticalGroup(
            sidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        layout_panel.add(sidebar4);
        sidebar4.setBounds(380, 790, 830, 20);

        lowerbar1.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout lowerbar1Layout = new javax.swing.GroupLayout(lowerbar1);
        lowerbar1.setLayout(lowerbar1Layout);
        lowerbar1Layout.setHorizontalGroup(
            lowerbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lowerbar1Layout.setVerticalGroup(
            lowerbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        layout_panel.add(lowerbar1);
        lowerbar1.setBounds(1180, 350, 30, 460);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        layout_panel.add(jSeparator1);
        jSeparator1.setBounds(400, 220, 750, 20);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Usuarios");
        layout_panel.add(jLabel1);
        jLabel1.setBounds(400, 140, 300, 70);

        jTable1.setForeground(new java.awt.Color(51, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "IdEmpleado", "PrimerNombre", "PrimerApellido", "NombreCompleto", "FechaInicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(51, 51, 51));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        layout_panel.add(jScrollPane1);
        jScrollPane1.setBounds(400, 230, 500, 220);

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("<html>\nAgregar\n<html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(10);
        layout_panel.add(jButton1);
        jButton1.setBounds(400, 480, 110, 50);

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        layout_panel.add(jButton2);
        jButton2.setBounds(530, 480, 110, 50);

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        layout_panel.add(jButton3);
        jButton3.setBounds(660, 480, 110, 50);

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        layout_panel.add(jButton4);
        jButton4.setBounds(790, 480, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel layout_panel;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel logo_label1;
    private javax.swing.JPanel lowerbar1;
    private javax.swing.JPanel nav_header;
    private javax.swing.JPanel nav_panel;
    private javax.swing.JPanel sidebar1;
    private javax.swing.JPanel sidebar2;
    private javax.swing.JPanel sidebar3;
    private javax.swing.JPanel sidebar4;
    // End of variables declaration//GEN-END:variables
}
